# Numpy functionnalities

# Import

In [97]:
import  numpy as np
from sklearn import datasets

# Sommaire

[I. Vecteur, matrice et array](#Partie1)
- [I.1. Création, séléction, description d'élément](#Partie1.1) 
- [I.2. Apprentissage et évaluation de modèles](#Partie1.2) 
- [I.3. Produit et calcul matriciel](#Partie1.3) 
- [I.4. Création de valeur aléatoire](#Partie1.4) 

## I. Vecteur, matrice et array <a class="anchor" id="Partie1"></a>

### I.1. Création, séléction, description et reconfiguration d'élément <a class="anchor" id="Partie1.1"></a>

In [98]:
vector_row=np.array([1,2,3])
vector_col=np.array([[1],[2],[3]])

In [99]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])

Gestion comme une liste

In [100]:
print(matrix[1,1], vector_row[2], vector_col[0][0])

5 3 1


In [101]:
print(matrix.reshape(1,12))
print(matrix.reshape(2,6))
print(matrix.reshape(2,-1)) #-1 permet de ne pas avoir préciser le nombre en question

[[1 2 3 4 5 6 7 8 9 7 8 9]]
[[1 2 3 4 5 6]
 [7 8 9 7 8 9]]
[[1 2 3 4 5 6]
 [7 8 9 7 8 9]]


In [102]:
print(matrix.shape, matrix.size, matrix.ndim)

(4, 3) 12 2


### I.2. Calcul d'attribut statistique de base <a class="anchor" id="Partie1.2"></a>

maximum et minimum d'une matrice <br>
Ligne maximum et colonne minimum d'une matrice <br>
Calcul de la moyenne, variance et écart-type dans la matrice (possible par ligne et colonne egalement)

In [103]:
print(np.max(matrix),np.min(matrix))
print(np.max(matrix,axis=0),np.min(matrix,axis=1))
print(np.mean(matrix),np.var(matrix),np.std(matrix))

9 1
[7 8 9] [1 4 7 7]
5.75 6.854166666666667 2.6180463454008347


### I.3. Produit et calcul matriciel <a class="anchor" id="Partie1.3"></a>

In [104]:
matrix.T #renvoie la transposée de matrix

array([[1, 4, 7, 7],
       [2, 5, 8, 8],
       [3, 6, 9, 9]])

In [105]:
vector_col.T #permet de trasnformer un vecteur colonne en ligne et vice versa

array([[1, 2, 3]])

In [106]:
print(np.dot(vector_row,vector_row)) #produit entre 2 vecteurs(ou matrice) donne la combinaison linéaire de chaque terme
print(vector_row @ vector_row)

14
14


In [107]:
print(matrix + matrix)
print(matrix - matrix)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### I.4. Création de valeur aléatoire <a class="anchor" id="Partie1.4"></a>

In [108]:
np.random.seed(0) #Permet d'avoir systématiquement les même nombres aléatoires à travers le notebook

In [109]:
print(np.random.random(5)) # Entre 0 et 1
print(np.random.randint(0,15,5)) # Des nombres entiers entre 0 et 15
print(np.random.normal(0,1,5)) # Des nombres d'une distribution normale de moyenne 0 et écart-type de 1
print(np.random.logistic(0,1,5)) # Des nombres d'une distribution logistique de moyenne 0 et écart-type de 1
print(np.random.uniform(0,10,5)) # Des nombres plus grand que 0 et plus petit que 10

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[5 2 4 7 6]
[-0.05503512 -0.10731045  1.36546718 -0.09769572 -2.42595457]
[ 1.62933678 -0.67491949  0.61101311 -0.53976806  3.10638027]
[1.4035078  8.70087258 4.73608045 8.00910752 5.2047748 ]
